project_id = "wsfdnwxsdmizxuurorpe"

[functions.fetch-stock-data]
verify_jwt = false

[functions.search-ticker]
verify_jwt = false

[functions.chat-with-robot]
verify_jwt = false

[functions.analyze-budget]
verify_jwt = false