export interface GlossaryTerm {
  term: string;
  definition: string;
  emoji?: string;
}

export const glossaryTerms: GlossaryTerm[] = [
  { term: "Assets", definition: "Everything of value that a person or company owns — this includes physical things (buildings, equipment) AND financial things (cash, stocks, patents). More assets = stronger base!" },
  { term: "Bear Market", definition: "When stock prices fall 20% or more from a recent high over a sustained period. Think of a bear swiping its paw downward. The official 20% drop is the widely used threshold.", emoji: "🐻" },
  { term: "Blue-Chip Stock", definition: "Shares in a large, financially sound company that is a recognized leader in its industry. Known for stability, not flashy growth. Think Johnson & Johnson or Coca-Cola." },
  { term: "Bond", definition: "A loan YOU give to a company or government. They promise to pay you back on a set date, plus regular interest payments along the way. Generally lower risk than stocks." },
  { term: "Broker", definition: "A person or platform licensed to buy and sell securities on your behalf. Modern apps like Fidelity or Schwab act as brokers. They may charge a commission (fee) per trade." },
  { term: "Bull Market", definition: "When stock prices rise 20% or more from a recent low over a sustained period. A bull charges upward — just like prices!", emoji: "🐂" },
  { term: "Diversification", definition: "Spreading your money across different stocks, sectors, or asset types to reduce risk. If one investment drops, others can offset the loss. Classic advice: don't put all your eggs in one basket!" },
  { term: "Dividend", definition: "A portion of a company's profits paid out to shareholders, usually in cash, on a regular schedule (quarterly is common). Not all companies pay dividends — it's their choice." },
  { term: "ETF (Exchange-Traded Fund)", definition: "A single investment that holds a collection of assets (like many stocks or bonds). It trades on a stock exchange just like a regular stock. Great for instant diversification!" },
  { term: "Equity", definition: "Ownership in a company. When you buy stock, you own equity — a small slice of that business. Equity value goes up or down with the company's performance." },
  { term: "Index", definition: "A tool that tracks the performance of a selected group of stocks. The S&P 500 tracks 500 large U.S. companies and is widely used as a benchmark for the overall market." },
  { term: "Inflation", definition: "The gradual rise in prices over time, which reduces what your money can buy. Investing is one way to try to grow your money faster than inflation erodes it." },
  { term: "IPO (Initial Public Offering)", definition: "The first time a private company offers its shares to the general public on a stock exchange. It's how companies raise money from outside investors for the first time. 🎉" },
  { term: "Liquidity", definition: "How easily and quickly an investment can be converted to cash without significantly affecting its price. Publicly traded stocks are considered highly liquid assets." },
  { term: "Market Cap (Market Capitalization)", definition: "The total market value of a company's outstanding shares. Formula: Share Price × Total Shares Outstanding. Used to classify companies as small-, mid-, or large-cap." },
  { term: "Portfolio", definition: "The complete collection of all investments you own — stocks, bonds, ETFs, cash, etc. Managing your portfolio means balancing risk and return across all your holdings." },
  { term: "Profit Margin", definition: "The percentage of revenue a company keeps as profit after all expenses are paid. A higher margin means the company is more efficient at turning sales into actual profit." },
  { term: "Return", definition: "The gain or loss made on an investment over a period of time, usually expressed as a percentage. A positive return means you made money; a negative return means you lost some." },
  { term: "Risk", definition: "The possibility that an investment loses value or performs worse than expected. In general, higher potential returns come with higher risk. Understanding your risk tolerance is a key part of smart investing." },
  { term: "Shares / Stock", definition: "A share is a unit of ownership in a corporation. When you buy stock in a company, you become a part-owner (shareholder) and may benefit if the company grows in value." },
  { term: "S&P 500", definition: "A stock market index tracking 500 of the largest publicly traded U.S. companies. It's one of the most widely followed benchmarks for the overall health of the U.S. stock market." },
  { term: "Volatility", definition: "A measure of how much a stock's price fluctuates over time. High volatility = big, unpredictable price swings. Low volatility = more stable, predictable price movement. 🌊" },
  { term: "Yield", definition: "The income generated by an investment, expressed as a percentage of its price. Example: a stock priced at $100 that pays a $5 annual dividend has a 5% dividend yield." },
];
